
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Daniel, Nabil, Tentin
 */
public class Signup extends javax.swing.JFrame {
  int flag=0;
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        // Group radio buttons for gender selection
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(jRadioButton2); // Female
        genderGroup.add(jRadioButton3); // Male
        
        jPasswordField1.setText("");
        
        jToggleButton2.addActionListener(e -> {
            if (jToggleButton2.isSelected()) {
                jPasswordField1.setEchoChar((char) 0); // Show password
                jToggleButton2.setText("Hide Pass");
            } else {
                jPasswordField1.setEchoChar('•'); // Hide password
                jToggleButton2.setText("Show Pass");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblemail = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 0, 50, 49));

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("BiauKaiTC", 1, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtname.setFont(new java.awt.Font("BiauKaiTC", 0, 18)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 339, -1));

        jButton2.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        jButton2.setText("Back To Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, 30));

        txtemail.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtemailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 339, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("BiauKaiTC", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Signup");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 118, 43));

        jLabel3.setFont(new java.awt.Font("BiauKaiTC", 1, 24)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 151, -1));

        jLabel4.setFont(new java.awt.Font("BiauKaiTC", 1, 24)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 151, -1));

        jLabel5.setFont(new java.awt.Font("BiauKaiTC", 1, 24)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 151, -1));

        jButton1.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        jButton1.setText("Signup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 80, 30));

        lblemail.setFont(new java.awt.Font("BiauKaiTC", 0, 14)); // NOI18N
        lblemail.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 260, 10));

        jPasswordField1.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 230, -1));

        jToggleButton2.setBackground(new java.awt.Color(0, 0, 0));
        jToggleButton2.setFont(new java.awt.Font("BiauKaiTC", 0, 14)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("Show Pass");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 100, -1));

        jLabel6.setFont(new java.awt.Font("BiauKaiTC", 1, 24)); // NOI18N
        jLabel6.setText("Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 151, -1));

        jRadioButton2.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        jRadioButton2.setText("Female");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("BiauKaiTC", 1, 18)); // NOI18N
        jRadioButton3.setText("Male");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 570, 310));

        jLabel7.setFont(new java.awt.Font("BiauKaiTC", 1, 70)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Please, Create Your Account");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 890, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lisa-anna-_5m2FlTsHa8-unsplash.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        int yes=JOptionPane.showConfirmDialog(this, "Are YOU SURE ?","Exit",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(yes==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(txtname.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Name field is required");
            txtname.requestFocus();
            return;
        }
    
    if(txtemail.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this,"Email field is required");
            txtemail.requestFocus();
            return;
        }
    
    if(!isValidEmail(txtemail.getText().trim())){
            JOptionPane.showMessageDialog(this,"Please enter a valid email address");
            txtemail.requestFocus();
            return;
        }
    
    if(new String(jPasswordField1.getPassword()).trim().equals("")){
            JOptionPane.showMessageDialog(this,"Password field is required");
            jPasswordField1.requestFocus();
            return;
        }
    
    if(!jRadioButton2.isSelected() && !jRadioButton3.isSelected()){
            JOptionPane.showMessageDialog(this,"Please select gender");
            return;
        }
    
    // Get selected gender
        String gender = jRadioButton3.isSelected() ? "Male" : "Female";
        
        PreparedStatement pst = null;
        ResultSet rs = null;
        Connection con = null;
        
    try {
            con = DBConnection.getConnection();
            
            // Check if email already exists
            pst = con.prepareStatement("SELECT * FROM users WHERE email = ?");
            pst.setString(1, txtemail.getText().toLowerCase().trim());
            rs = pst.executeQuery();
            
            if(rs.next()){
                JOptionPane.showMessageDialog(this,"This email is already registered. Please use another email ID");
                txtemail.requestFocus();
            } else {
                // Insert new user
                pst = con.prepareStatement("INSERT INTO users(name, email, password, gender) VALUES(?, ?, ?, ?)");
                pst.setString(1, txtname.getText().trim());
                pst.setString(2, txtemail.getText().toLowerCase().trim());
                pst.setString(3, new String(jPasswordField1.getPassword()));
                pst.setString(4, gender);
                
                int result = pst.executeUpdate();
                if(result > 0) {
                    JOptionPane.showMessageDialog(this, "Registration Successful!\nYou can now login with your credentials.");
                    clearFields();
                    new SignIn().setVisible(true);
                    this.dispose(); // Close signup window
                }
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
            ex.printStackTrace();
        } finally {
            // Close resources
            try {
                if(rs != null) rs.close();
                if(pst != null) pst.close();
                if(con != null) con.close();
            } catch(SQLException ex) {
                ex.printStackTrace();
            }
        }                                                            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new SignIn().setVisible(true);
        this.dispose(); // Close current window    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        txtemail.requestFocus();// TODO add your handling code here:
        }
    }//GEN-LAST:event_txtnameKeyPressed
 
    private void txtemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jPasswordField1.requestFocus();
        }                                   
    }//GEN-LAST:event_txtemailKeyPressed

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        String email = txtemail.getText().toLowerCase().trim();
        txtemail.setText(email); 

        if(email.equals("")) {
            lblemail.setText("");
            return;
        }

        if(isValidEmail(email)) {
            lblemail.setText("");
        } else {
            lblemail.setText("Invalid Email ID");
        }
    }//GEN-LAST:event_txtemailKeyReleased

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jRadioButton3.requestFocus(); // Focus on gender selection
            }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed
    // Helper method to validate email
    private boolean isValidEmail(String email) {
        if(email == null || email.trim().equals("")) {
            return false;
        }
        
        int atIndex = email.indexOf('@');
        if(atIndex == -1 || atIndex == 0 || atIndex == email.length() - 1) {
            return false;
        }
        
        String[] parts = email.split("@");
        if(parts.length != 2) {
            return false;
        }
        
        String domain = parts[1];
        return domain.equalsIgnoreCase("gmail.com") || 
               domain.equalsIgnoreCase("yahoo.com") || 
               domain.equalsIgnoreCase("outlook.com") ||
               domain.contains(".");
    }
    
    // Helper method to clear all fields
    private void clearFields() {
        txtname.setText("");
        txtemail.setText("");
        jPasswordField1.setText("");
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        lblemail.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblemail;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
